% =====================================================================
%  generate_figures.m  (auto-generated by redraw_cec2017.py)
%  Reproduce CEC2017 (Dim = 100) Boxplot and Convergence figures as TIFF.
%   - Global font size : 18 pt
%   - Output resolution: 330 DPI, LZW-compressed TIFF
%   - Convergence plot: NO inset (zoom) subplot
%   - Convergence x-axis: starts at 0, ends at the last iteration (data-driven)
%  USAGE: keep script in project folder, put *_Best_Values.xlsx and
%  *_Avg_Convergence.xlsx pairs inside 'data/', then run: generate_figures
%  REQUIREMENTS: MATLAB R2020a+ (uses exportgraphics).
% =====================================================================
clc; clear;
FONT_SIZE = 18;
DPI       = 330;
ALGOS = {'iPWO','PWO','SFOA','DRA','MGO','LCA','DE','PSO','GWO'};
COLORS = [ 0.894 0.102 0.110; 0.216 0.494 0.722; 0.302 0.686 0.290; ...
           0.596 0.306 0.639; 1.000 0.498 0.000; 0.000 0.749 0.769; ...
           0.773 0.106 0.490; 0.420 0.725 0.839; 0.588 0.588 0.588];
MARKERS = {'*','o','^','d','s','v','+','x','p'};
script_dir = fileparts(mfilename('fullpath'));
data_dir   = fullfile(script_dir, 'data');
out_dir    = fullfile(script_dir, 'figures');
if ~exist(out_dir, 'dir'), mkdir(out_dir); end
xlsx_files = dir(fullfile(data_dir, '*_Best_Values.xlsx'));
if isempty(xlsx_files), error('No *_Best_Values.xlsx in data/.'); end
func_ids = zeros(numel(xlsx_files), 1);
for k = 1:numel(xlsx_files)
    tk = regexp(xlsx_files(k).name, 'F(\d+)_Dim100', 'tokens');
    func_ids(k) = str2double(tk{1}{1});
end
func_ids = sort(func_ids);
fprintf('Generating figures for %d functions (%d pt, %d DPI)...\n', numel(func_ids), FONT_SIZE, DPI);
for fi = 1:numel(func_ids)
    fid = func_ids(fi);
    bw = fullfile(data_dir, sprintf('CEC2017_F%%d_Dim100_Best_Values.xlsx', fid));
    data = readmatrix(bw, 'NumHeaderLines', 1);
    figure('Units','inches','Position',[0 0 8 5]);
    boxplot(data, 'Labels', ALGOS, 'Widths', 0.55, 'PlotStyle', 'traditional');
    ax = gca; ax.FontSize = FONT_SIZE;
    try
        h = findobj(ax, 'Tag', 'Box');
        for i = 1:numel(h)
            h(i).FaceColor = COLORS(i,:); h(i).FaceAlpha = 0.65;
            h(i).EdgeColor = 'k'; h(i).LineWidth = 0.7;
        end
    catch, end
    ylabel('Best value (per run)', 'FontSize', FONT_SIZE);
    title('Boxplot of Best Values (51 runs)', 'FontSize', FONT_SIZE, 'FontWeight','bold');
    grid on; ax.YGrid = 'on'; ax.GridLineStyle = '--';
    exportgraphics(gcf, fullfile(out_dir, sprintf('CEC2017_F%%d_Dim100_Boxplot_BestValues.tif', fid)), 'Resolution', DPI, 'ContentType', 'image');
    close;
    cw = fullfile(data_dir, sprintf('CEC2017_F%%d_Dim100_Avg_Convergence.xlsx', fid));
    cdata = readmatrix(cw, 'NumHeaderLines', 1);
    nfe = size(cdata, 1);
    fe  = (0:nfe-1).';
    figure('Units','inches','Position',[0 0 9 5.5]); hold on;
    for a = 1:9
        semilogy(fe, cdata(:,a), 'Color', COLORS(a,:), 'Marker', MARKERS{a}, ...
                 'MarkerIndices', 1:round(nfe/20):nfe, 'MarkerSize', 5, 'LineWidth', 1.2);
    end
    hold off; ax = gca; ax.FontSize = FONT_SIZE;
    xlabel('Iteration', 'FontSize', FONT_SIZE);
    ylabel('Best Score', 'FontSize', FONT_SIZE);
    title(sprintf('CEC2017 F%%d, Dim=100', fid), 'FontSize', FONT_SIZE, 'FontWeight','bold');
    legend(ALGOS, 'Location', 'northeast', 'FontSize', FONT_SIZE-2, 'BoxAlpha', 0.9);
    xlim([0 nfe-1]);
    grid on; ax.YGrid = 'on'; ax.GridLineStyle = '--'; ax.MinorGridLineStyle = ':';
    exportgraphics(gcf, fullfile(out_dir, sprintf('CEC2017_F%%d_Dim100_Convergence.tif', fid)), 'Resolution', DPI, 'ContentType', 'image');
    close;
    fprintf('  F%%d done\n', fid);
end
fprintf('All %d figures written to: %s\n', numel(func_ids), out_dir);
